package:
  name: flask_socket_util
  version: "0.0.13"

source:
  git_url: https://github.com/slaclab/flask_socket_util.git
  git_tag: "0.0.13"

build:
  noarch: python
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
    - flask >=1.0.0
    - eventlet >=0.23.0
    - flask-socketio >=3.0.0
    - kafka-python
  run:
    - python
    - setuptools
    - flask >=1.0.0
    - eventlet >=0.23.0
    - flask-socketio >=3.0.0
    - kafka-python

about:
  home: https://github.com/slaclab/flask_socket_util
  license: MIT License
