package:
  name: flask_socket_util
  version: "0.0.2"

source:
  git_url: https://github.com/slaclab/flask_socket_util.git
  git_tag: "0.0.2"

build:
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
    - flask-socketio
    - kafka-python
  run:
    - python
    - setuptools
    - flask-socketio
    - kafka-python

about:
  home: https://github.com/slaclab/flask_socket_util
  license: MIT License